# Numpy

Numpy Arrays

In [ ]:
# creating array

import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6,7,8,9,0]])
print(a)
print(type(a))

# change shape 
a.reshape(5,2)
print(a.shape)
a.shape = (5,2)
print(a.shape)



[[1 2 3 4 5]
 [6 7 8 9 0]]
<class 'numpy.ndarray'>
(2, 5)
(5, 2)


In [7]:
# initialize array with zeros
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# same number array
a = np.full((2, 3), 5)
print(a)

# range of array
b = np.arange(0, 10, 2)
print(b)

# random array
c = np.random.randint(0, 25,2)
print(c)

[[5 5 5]
 [5 5 5]]
[0 2 4 6 8]
[3 8]


Joining Numpy Arrays

In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,4,3,2,1])

# Vstack | vertical stack
c = np.vstack((a,b))
print(c)

# Hstack | horizontal stack
d = np.hstack((a,b))
print(d)

# Cloums_stack 
e = np.column_stack((a,b))
print(e)



[[1 2 3 4 5]
 [5 4 3 2 1]]


Intersection and Differences

In [35]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,7,8,2,12])

# intersection 
x = np.intersect1d(a,b)
print(x)

# Differences
y = np.setdiff1d(a,b) # it will give elements of a that are not present in b
print(y)

[2 5]
[1 3 4]


Array Manthematics

In [ ]:
a = np.array([1,2]) 
b = np.array([5,7])

# Array Addition
x = np.sum([a,b], axis=0) # axis = 0 adds col value od a and 2 | axis=1 adds elements of a and b and give a array of both the addition 
print(x)


[6 9]


In [ ]:
#Operations

a = np.array([10,20,30,40,50])

#add
a = a + 1
a

# same fo r -, *, /

array([11, 21, 31, 41, 51])

In [3]:
# Math Functions
a = np.array([10,20,30,40,50])

np.mean(a)
np.std(a)
np.median(a)



np.float64(30.0)

Saving and loadingd numpy arrays

In [6]:
a = np.array([10,20,30,40,50])

np.save('myArray', a)

b = np.load('myArray.npy')
b

array([10, 20, 30, 40, 50])

In [2]:
import numpy as np

class Test:
    def two_sum(self):
        target = 9
        arr = np.array([2,12,4,15,7,8,3,10,6,9,11])  
        arr.sort()
        
        l = 0
        r = len(arr) - 1

        while l < r:
            s = arr[l] + arr[r]
            
            if s == target:
                return l, r
            
            elif s < target:
                l += 1
            else:
                r -= 1
        
        return None

run = Test()
print(run.two_sum())



(0, 4)
